language: node_js
node_js:
  - 12
jobs:
  include:
    - stage: test
      name: "Unit Tests"
    - stage: deploy
      name: "Deploy to Production"
      script: npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: build
        github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
        keep_history: true
        on:
          branch: master
