language: node_js
node_js:
  - 12
jobs:
  include:
    - stage: test
      name: "Unit Tests"
    - stage: deploy
      name: "Deploy to Production"
      deploy:
        provider: script
        script: npm run deploy
        skip_cleanup: true
        on:
          branch: master
