steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install', '--prefix', 'client']
- name: 'gcr.io/cloud-builders/npm'
  args: ['install', '--prefix', 'server']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build', '--prefix', 'server']
- name: google/cloud-sdk:230.0.0
  entrypoint: 'gcloud'
  args: ['app', 'deploy']
  dir: 'server'